# Use a imagem oficial do Node.js como imagem base
FROM node:16 AS build
# Crie um diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copie o package.json e o package-lock.json (se existir)
COPY package*.json ./

# Instale as dependências do aplicativo
RUN npm install

# Copie o restante do código da aplicação
COPY . .

# Exponha a porta em que a aplicação irá rodar
EXPOSE 5000

# Comando para rodar a aplicação
CMD ["npm", "start"]
