version: '3'
services:
  react-app:
    build: .
    ports:
      - "3000:80"
    networks:
      - minha-rede
 
  mongodb:
    image: mongo:latest
    networks:
      - minha-rede
 
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
    networks:
      - minha-rede
    depends_on:
      - mongodb
 
networks:
  minha-rede:
    driver: bridge
