FROM jenkins/jenkins:latest
FROM node:16 AS build

WORKDIR /app

USER root

RUN apt-get update && apt-get install -y \
    curl \
    git \
    nodejs \
    npm \
    build-essential \
    mailutils

COPY package.json package-lock.json  

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

USER jenkins
